services:
  mongo:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    links:
      - mongo
    ports:
      - "8099:8081"
    container_name: "mongo-express"
